os:
  - linux

language: cpp

sudo: required

compiler:
  - gcc
  - clang

cache:
    apt: true

before_script:
  - autoreconf -iv -I `pwd`/m4
  - ./configure

script:
  - make

branches:
  only:
    - master

notifications:
  email:
    on_success: change
    on_failure: always
